name: Deploy when pushing on main

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "Upload script"

    steps:
      - uses: actions/checkout@v6
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@v6
        with: { node-version: lts/*, cache: pnpm }
      - run: pnpm install
      - run: pnpm build

      - name: Deploy Script to Bunny Edge Scripting
        uses: BunnyWay/actions/deploy-script@main
        with:
          script_id: ${{ secrets.SCRIPT_ID }}
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          file: ".output/bunny-edge-scripting.mjs"
